### ISSUE TITLE
部署heroku显示err: TypeError: source.replace is not a function

### ISSUE THREAD

**Issue by DaoChen6** [auroral-ui/hexo-theme-aurora#108]
部署heroku显示err: TypeError: source.replace is not a function
at Object.exports.parse (C:\Users\Administrator\blog\node_modules\swig\lib\parser.js:438:19)
      at exports.Swig.parse (C:\Users\Administrator\blog\node_modules\swig\lib\swig.js:354:19)
      at Object.precompile (C:\Users\Administrator\blog\node_modules\swig\lib\swig.js:486:23)
      at Object.compile (C:\Users\Administrator\blog\node_modules\swig\lib\swig.js:606:16)
      at commitMessage (C:\Users\Administrator\blog\node_modules\hexo-deployer-heroku\lib\deployer.js:100:15)
      at Hexo.module.exports (C:\Users\Administrator\blog\node_modules\hexo-deployer-heroku\lib\deployer.js:25:17)
      at Hexo.tryCatcher (C:\Users\Administrator\blog\node_modules\bluebird\js\release\util.js:16:23)
      at Hexo.<anonymous> (C:\Users\Administrator\blog\node_modules\bluebird\js\release\method.js:15:34)
      at C:\Users\Administrator\blog\node_modules\hexo\lib\plugins\console\deploy.js:53:20
      at tryCatcher (C:\Users\Administrator\blog\node_modules\bluebird\js\release\util.js:16:23)
      at Object.gotValue (C:\Users\Administrator\blog\node_modules\bluebird\js\release\reduce.js:166:18)
      at Object.gotAccum (C:\Users\Administrator\blog\node_modules\bluebird\js\release\reduce.js:155:25)
      at Object.tryCatcher (C:\Users\Administrator\blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\Administrator\blog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\Administrator\blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromiseCtx (C:\Users\Administrator\blog\node_modules\bluebird\js\release\promise.js:641:10)
      at _drainQueueStep (C:\Users\Administrator\blog\node_modules\bluebird\js\release\async.js:97:12)
      at _drainQueue (C:\Users\Administrator\blog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Users\Administrator\blog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\blog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:461:21)

**Comment by DaoChen6** [comment]
不好意思鲁莽了，没加空格
