### ISSUE TITLE
加载js脚本失败

### ISSUE THREAD

**Issue by MrCaiDev** [auroral-ui/hexo-theme-aurora#129]
直接使用默认的config.yml也不行，打开网页全是加载中状态。
ERROR {
  err: Error: Cannot find module 'truncate-html'
  Require stack:
  - D:\Codes\Blog\themes\aurora\scripts\lib\helpers\truncate-html.js
  - D:\Codes\Blog\themes\aurora\scripts\lib\helpers\mapper.js
  - D:\Codes\Blog\themes\aurora\scripts\lib\generators\category.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
      at Function.Module._load (node:internal/modules/cjs/loader:778:27)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:94:18)
      at Object.<anonymous> (D:\Codes\Blog\themes\aurora\scripts\lib\helpers\truncate-html.js:1:18)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:94:18)
      at Object.<anonymous> (D:\Codes\Blog\themes\aurora\scripts\lib\helpers\mapper.js:2:22)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at req (D:\Codes\Blog\node_modules\hexo\lib\hexo\index.js:292:23)
      at D:\Codes\Blog\themes\aurora\scripts\lib\generators\category.js:6:5
      at D:\Codes\Blog\node_modules\hexo\lib\hexo\index.js:305:14
      at tryCatcher (D:\Codes\Blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\Codes\Blog\node_modules\bluebird\js\release\promise.js:547:31) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'D:\\Codes\\Blog\\themes\\aurora\\scripts\\lib\\helpers\\truncate-html.js',
      'D:\\Codes\\Blog\\themes\\aurora\\scripts\\lib\\helpers\\mapper.js',
      'D:\\Codes\\Blog\\themes\\aurora\\scripts\\lib\\generators\\category.js'
    ]
  }
} Script load failed: %s themes\aurora\scripts\lib\generators\category.js

**Comment by MrCaiDev** [comment]
![image](https://user-images.githubusercontent.com/78269445/129140833-0a334df0-f251-4a93-bcab-10d3df7051bd.png)

**Comment by MrCaiDev** [comment]
解决了，用npm重装了一遍

**Comment by JOSHUAWENJZ** [comment]
@MrCaiDev 你好，你是用npm重装了什么东西，解决的你的问题，我也碰到类似的问题，目前还没有解决。

**Comment by MrCaiDev** [comment]
> @MrCaiDev 你好，你是用npm重装了什么东西，解决的你的问题，我也碰到类似的问题，目前还没有解决。

抱歉，时间过久，已经不记得了；但我推测是重装aurora，我没有重装过其他相关的东西

**Comment by coco-droid** [comment]
I have the same problem

**Comment by btheNerd** [comment]
I just had the same problem, however, I simply solved it by running
`` yarn add hexo-theme-aurora
     hexo cl && hexo g && hexo d 
``
in terminal. It didn't change any of config files.
the solution of @mrcaidev was proved.

**Comment by MunoDevelop** [comment]
It's happen when i forcely  use audit fix , reinstall aurora fixed it
