### ISSUE TITLE
不添加CDN配置报错，添加了CDN仍然报错

### ISSUE THREAD

**Issue by ccpwcn** [auroral-ui/hexo-theme-aurora#159]
site_meta中没有配置CDN时，提示错误如下：
```
[Aurora config error]: cdn in site_meta is not configured, please provide the cdn configure in _config.aurora.yml
```

当在site_meta中配置了CDN时：
```yml
site_meta:
  cdn: cn
```
报错如下：
```
INFO  Validating config
ERROR {
  err: TypeError: Cannot read property 'enable' of undefined
      at module.exports (E:\code\11ms.cn.hexo\node_modules\hexo-theme-aurora\scripts\lib\injector\index.js:53:28)
      at E:\code\11ms.cn.hexo\node_modules\hexo-theme-aurora\scripts\index.js:5:26
      at E:\code\11ms.cn.hexo\node_modules\hexo\lib\hexo\index.js:305:14
      at tryCatcher (E:\code\11ms.cn.hexo\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\code\11ms.cn.hexo\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\code\11ms.cn.hexo\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (E:\code\11ms.cn.hexo\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (E:\code\11ms.cn.hexo\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (E:\code\11ms.cn.hexo\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (E:\code\11ms.cn.hexo\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\code\11ms.cn.hexo\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\code\11ms.cn.hexo\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:464:21)
```

**Comment by uyloal** [comment]
你是不是删掉/注释了某个配置项
