### ISSUE TITLE
错误读取文章front-matter导致的错误

### ISSUE THREAD

**Issue by kcn3388** [auroral-ui/hexo-theme-aurora#25]
log:
ERROR ERROR {
  err: TypeError: Cannot read property 'cdn' of undefined
      at module.exports (/home/kcn3388/hexo/themes/aurora/scripts/lib/injector/index.js:16:29)
      at /home/kcn3388/hexo/themes/aurora/scripts/index.js:4:26
      at /home/kcn3388/hexo/node_modules/hexo/lib/hexo/index.js:305:14
      at tryCatcher (/home/kcn3388/hexo/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/kcn3388/hexo/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/kcn3388/hexo/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/kcn3388/hexo/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/kcn3388/hexo/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/home/kcn3388/hexo/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/kcn3388/hexo/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/kcn3388/hexo/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/kcn3388/hexo/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:439:21)
} Script load failed: %s themes/aurora/scripts/index.js
{
  err: TypeError: Cannot read property 'cdn' of undefined
      at module.exports (/home/kcn3388/hexo/themes/aurora/scripts/lib/injector/index.js:16:29)
      at /home/kcn3388/hexo/themes/aurora/scripts/index.js:4:26
      at /home/kcn3388/hexo/node_modules/hexo/lib/hexo/index.js:305:14
      at tryCatcher (/home/kcn3388/hexo/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/kcn3388/hexo/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/kcn3388/hexo/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/kcn3388/hexo/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/kcn3388/hexo/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/home/kcn3388/hexo/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/kcn3388/hexo/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/kcn3388/hexo/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/kcn3388/hexo/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:439:21)
} Script load failed: %s themes/aurora/scripts/index.js
INFO  Start processing
FATAL {
  err: TypeError: Cannot read property 'KMurasaki' of null
      at authorMapper (/home/kcn3388/hexo/themes/aurora/scripts/lib/helpers/mapper.js:41:50)
      at postMapper (/home/kcn3388/hexo/themes/aurora/scripts/lib/helpers/mapper.js:33:13)
      at /home/kcn3388/hexo/themes/aurora/scripts/lib/generators/post.js:33:21
      at _Query.forEach (/home/kcn3388/hexo/node_modules/warehouse/lib/query.js:36:7)
      at PostGenerator.transform (/home/kcn3388/hexo/themes/aurora/scripts/lib/generators/post.js:32:15)
      at new PostGenerator (/home/kcn3388/hexo/themes/aurora/scripts/lib/generators/post.js:13:10)
      at generator (/home/kcn3388/hexo/themes/aurora/scripts/lib/generators/index.js:91:19)
      at Hexo.<anonymous> (/home/kcn3388/hexo/themes/aurora/scripts/lib/generators/index.js:79:12)
      at Hexo.tryCatcher (/home/kcn3388/hexo/node_modules/bluebird/js/release/util.js:16:23)
      at Hexo.<anonymous> (/home/kcn3388/hexo/node_modules/bluebird/js/release/method.js:15:34)
      at /home/kcn3388/hexo/node_modules/hexo/lib/hexo/index.js:405:22
      at tryCatcher (/home/kcn3388/hexo/node_modules/bluebird/js/release/util.js:16:23)
      at MappingPromiseArray._promiseFulfilled (/home/kcn3388/hexo/node_modules/bluebird/js/release/map.js:68:38)
      at MappingPromiseArray.PromiseArray._iterate (/home/kcn3388/hexo/node_modules/bluebird/js/release/promise_array.js:115:31)
      at MappingPromiseArray.init (/home/kcn3388/hexo/node_modules/bluebird/js/release/promise_array.js:79:10)
      at MappingPromiseArray._asyncInit (/home/kcn3388/hexo/node_modules/bluebird/js/release/map.js:37:10)
      at _drainQueueStep (/home/kcn3388/hexo/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/home/kcn3388/hexo/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/kcn3388/hexo/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/kcn3388/hexo/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:439:21)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

kmurasaki是我文章设置的第三方作者名，代码为:
author: Kmurasaki

**Comment by TriDiamond** [comment]
在群中解决了。
