### ISSUE TITLE
Valine comment plugin does not work with LeanCloud International

### ISSUE THREAD

**Issue by makinbacon21** [auroral-ui/hexo-theme-aurora#255]
As far as I can tell, both listed comments plugins don't work very well, but the `valine` plugin refuses to work, at least when I use a key from LeanCloud International.
Console upon page load:
```
index_prod-2141a5c8.js:1  ReferenceError: _ is not defined
    at setup (index_prod-2141a5c8.js:34:28892)
    at cn (index_prod-2141a5c8.js:1:13506)
    at Yf (index_prod-2141a5c8.js:1:52630)
    at Gf (index_prod-2141a5c8.js:1:52415)
    at $ (index_prod-2141a5c8.js:1:39684)
    at m (index_prod-2141a5c8.js:1:39577)
    at C (index_prod-2141a5c8.js:1:36439)
    at D (index_prod-2141a5c8.js:1:37895)
    at Y (index_prod-2141a5c8.js:1:46067)
    at Object.process (index_prod-2141a5c8.js:1:46101)
Y0 @ index_prod-2141a5c8.js:1
index_prod-2141a5c8.js:77  Aurora is developed by TriDiamond https://github.com/auroral-ui/hexo-theme-aurora
index_prod-2141a5c8.js:67  ReferenceError: AV is not defined
    at a7.initLeancloud (index_prod-2141a5c8.js:67:2774)
    at new a7 (index_prod-2141a5c8.js:67:2374)
    at s (index_prod-2141a5c8.js:67:5861)
    at index_prod-2141a5c8.js:1:23998
    at cn (index_prod-2141a5c8.js:1:13506)
    at wt (index_prod-2141a5c8.js:1:13585)
    at Mo.t.__weh.t.__weh (index_prod-2141a5c8.js:1:23878)
    at Gs (index_prod-2141a5c8.js:1:2110)
    at Jr.z [as fn] (index_prod-2141a5c8.js:1:40446)
    at Jr.run (index_prod-2141a5c8.js:1:4979)
initLeancloud @ index_prod-2141a5c8.js:67
index_prod-2141a5c8.js:67  Uncaught (in promise) ReferenceError: AV is not defined
    at a7.queryAll (index_prod-2141a5c8.js:67:3378)
    at index_prod-2141a5c8.js:67:3908
    at new Promise (<anonymous>)
    at a7.getRecentComments (index_prod-2141a5c8.js:67:3887)
    at s (index_prod-2141a5c8.js:67:6080)
    at index_prod-2141a5c8.js:1:23998
    at cn (index_prod-2141a5c8.js:1:13506)
    at wt (index_prod-2141a5c8.js:1:13585)
    at Mo.t.__weh.t.__weh (index_prod-2141a5c8.js:1:23878)
    at Gs (index_prod-2141a5c8.js:1:2110)
index_prod-2141a5c8.js:1  ReferenceError: Valine is not defined
    at a (Comment-14d48132.js:2:751)
    at Comment-14d48132.js:2:1325
    at index_prod-2141a5c8.js:1:23998
    at cn (index_prod-2141a5c8.js:1:13506)
    at wt (index_prod-2141a5c8.js:1:13585)
    at Mo.t.__weh.t.__weh (index_prod-2141a5c8.js:1:23878)
    at Rc (index_prod-2141a5c8.js:1:14879)
    at Nc (index_prod-2141a5c8.js:1:15186)
Y0 @ index_prod-2141a5c8.js:1
index_prod-2141a5c8.js:1  ReferenceError: Prism is not defined
    at d (Post-1a65712f.js:1:1077)
```

**Comment by bennyxguo** [comment]
Hey @makinbacon21, thanks for posting an issue. Have you try `hexo clean && hexo generate && hexo server` ? This looks like the latest scripts are not generated. Just to be sure you have installed the latest `hexo-plugin-aurora` right?

**Comment by makinbacon21** [comment]
*sigh* you are correct. was missing some packs and wasnt cleaning and generating--works now :)
