### ISSUE TITLE
安装主题后报错language属性未定义,hexo命令无法使用

### ISSUE THREAD

**Issue by Allensht** [auroral-ui/hexo-theme-aurora#257]
报错内容如下：
ERROR Plugin load failed: hexo-plugin-aurora
TypeError: Cannot read property 'language' of undefined
    at module.exports (/home/allensht/hexo/blog/node_modules/hexo-plugin-aurora/lib/filters/index.js:55:33)
    at /home/allensht/hexo/blog/node_modules/hexo-plugin-aurora/index.js:4:25
    at /home/allensht/hexo/blog/node_modules/hexo/lib/hexo/index.js:305:14
    at tryCatcher (/home/allensht/hexo/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/allensht/hexo/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/allensht/hexo/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/allensht/hexo/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/allensht/hexo/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/allensht/hexo/blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/allensht/hexo/blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/allensht/hexo/blog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/allensht/hexo/blog/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
![Snipaste_2023-07-31_11-44-26](https://github.com/auroral-ui/hexo-theme-aurora/assets/119091958/b5f3ee70-b2da-4cc6-bcc5-69f621a21c1f)

**Comment by bennyxguo** [comment]
配置里面的 lang 没有填吧？那个目前没有做默认值。后期加一下。现在的话填一下 lang 值吧。

**Comment by bennyxguo** [comment]
这个是因为你没有使用主题配置模版，可以把这里的配置模版复制下来 https://github.com/auroral-ui/hexo-theme-aurora/blob/main/_config.yml。然后在你的博客根目录创建一个 `_config.aurora.yml` 然后黏贴进去。
