### ISSUE TITLE
代码高亮失效

### ISSUE THREAD

**Issue by 735690757** [auroral-ui/hexo-theme-aurora#304]
我的主题版本从1.5升级到2.3.1后代码高亮失效，之前是正常的，这个应该怎么办呢

**Comment by bennyxguo** [comment]
先试试  hexo clean && hexo g

**Comment by 735690757** [comment]
> 先尝试hexo clean && hexo g 有线上地址，发一下线上博客地址。
刚才试了一下，还是不行。
https://735690757.github.io/

**Comment by bennyxguo** [comment]
> > 先尝试hexo clean && hexo g 有线上地址，发一下线上博客地址。
> > 刚才试了一下，还是不行。
> > https://735690757.github.io/

你的 Dia 机器人的配置有问题。导致代码执行报错，影响到其他代码正常执行。

**Comment by 735690757** [comment]
确实确实，现在我配置好了dia，但是高亮还是没有
![屏幕截图 2023-08-15 144714](https://github.com/auroral-ui/hexo-theme-aurora/assets/51825900/299f55bc-9dba-4531-a798-7fe0d9082865)

**Comment by 735690757** [comment]
![屏幕截图 2023-08-15 145238](https://github.com/auroral-ui/hexo-theme-aurora/assets/51825900/50f244c2-e2b8-4608-926a-13e6f0c90882)

**Comment by bennyxguo** [comment]
> 确实确实，现在我配置好了dia，但是高亮还是没有 ![屏幕截图 2023-08-15 144714](https://user-images.githubusercontent.com/51825900/260645729-299f55bc-9dba-4531-a798-7fe0d9082865.png)

<img width="810" alt="image" src="https://github.com/auroral-ui/hexo-theme-aurora/assets/24708758/d1f72be0-8512-4e42-87be-755d6a00922a">

这里提示你了，看看这个配置：

**Comment by 735690757** [comment]
现在一个报错没有，他就是不高亮了（笑哭）
![屏幕截图 2023-08-15 150859](https://github.com/auroral-ui/hexo-theme-aurora/assets/51825900/dda99371-77ed-4af5-93bd-952f8e935e00)
![屏幕截图 2023-08-15 150953](https://github.com/auroral-ui/hexo-theme-aurora/assets/51825900/3c1cf710-5c14-45d0-8155-8f0b8529cdec)

**Comment by bennyxguo** [comment]
你 ctrl + shift + R 刷新一下页面试试

**Comment by 735690757** [comment]
还是不行啊QWQ，大佬你先忙吧，我再研究研究

**Comment by xiaoyuebao** [comment]
看看你的hexo版本，[禁用代码](https://hexo.io/zh-cn/docs/syntax-highlight#%E7%A6%81%E7%94%A8)

禁用
v7.0.0及以下：
```
# _config.yml
highlight:
  enable: false
prismjs:
  enable: false
```
v7.0.0及以上：
```
# _config.yml
syntax_highlighter: # empty
```

**Comment by xiaoyuebao** [comment]
@bennyxguo 看看你的hexo版本，[禁用代码](https://hexo.io/zh-cn/docs/syntax-highlight#%E7%A6%81%E7%94%A8)

禁用
v7.0.0及以下：
```
# _config.yml
highlight:
  enable: false
prismjs:
  enable: false
```
v7.0.0及以上：
```
# _config.yml
syntax_highlighter: # empty
```

**Comment by Anixuil** [comment]
"hexo": "^7.3.0",
"hexo-theme-aurora": "^2.5.3",
"hexo-plugin-aurora": "^1.8.4",

TypeError: code.split is not a function
Please report this to https://github.com/markedjs/marked.
    at codeToThemedTokens (D:\code\self\frontend\blog-ui\node_modules\shiki\dist\index.js:3191:26)
    at Object.codeToHtml (D:\code\self\frontend\blog-ui\node_modules\shiki\dist\index.js:3212:20)
    at filterIntoShiki (D:\code\self\frontend\blog-ui\node_modules\hexo-plugin-aurora\lib\highlighter\index.js:56:32)
    at renderer.code (D:\code\self\frontend\blog-ui\node_modules\hexo-plugin-aurora\lib\highlighter\index.js:127:14)
    at renderer.<computed> [as code] (D:\code\self\frontend\blog-ui\node_modules\marked\lib\marked.cjs:2341:48)
    at _Parser.parse (D:\code\self\frontend\blog-ui\node_modules\marked\lib\marked.cjs:2032:42)
    at parse (D:\code\self\frontend\blog-ui\node_modules\marked\lib\marked.cjs:1992:23)
    at Marked.parse (D:\code\self\frontend\blog-ui\node_modules\marked\lib\marked.cjs:2485:28)
    at Function.marked [as parse] (D:\code\self\frontend\blog-ui\node_modules\marked\lib\marked.cjs:2519:27)
    at module.exports (D:\code\self\frontend\blog-ui\node_modules\hexo-renderer-marked\lib\renderer.js:279:27)
    at Hexo.tryCatcher (D:\code\self\frontend\blog-ui\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\code\self\frontend\blog-ui\node_modules\bluebird\js\release\method.js:15:34)
    at D:\code\self\frontend\blog-ui\node_modules\hexo\dist\hexo\render.js:73:28
    at tryCatcher (D:\code\self\frontend\blog-ui\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\code\self\frontend\blog-ui\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\code\self\frontend\blog-ui\node_modules\bluebird\js\release\promise.js:604:18)
