### ISSUE TITLE
Code Filtering Error V2.5

### ISSUE THREAD

**Issue by Tim-Saijun** [auroral-ui/hexo-theme-aurora#364]
今天去升级2.5，
在generate的时候，报错如下：
```bash
[Aurora Code Filtering Error] Code language: [C++] is not supported.
[Aurora Code Filtering Error] Code language: [C++] is not supported.
[Aurora Code Filtering Error] Code language: [txt] is not supported.
[Aurora Code Filtering Error] Code language: [txt] is not supported.
[Aurora Code Filtering Error] Code language: [C++] is not supported.
[Aurora Code Filtering Error] Code language: [C++] is not supported.
[Aurora Code Filtering Error] Code language: [C] is not supported.
[Aurora Code Filtering Error] Code language: [C] is not supported.
[Aurora Code Filtering Error] Code language: [C] is not supported.
[Aurora Code Filtering Error] Code language: [C] is not supported.
[Aurora Code Filtering Error] Code language: [C] is not supported.
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: Can't find handler for document
    at HandlerList.handlesDocument (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/mathjax-full/js/core/HandlerList.js:60:15)
    at HandlerList.document (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/mathjax-full/js/core/HandlerList.js:64:21)
    at Object.document (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/mathjax-full/js/mathjax.js:11:41)
    at /home/runner/work/BlogByHexo/BlogByHexo/node_modules/hexo-filter-mathjax/lib/filter.js:42:26
    at Hexo.<anonymous> (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/hexo-filter-mathjax/index.js:20:18)
    at Hexo.tryCatcher (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/bluebird/js/release/method.js:15:34)
    at /home/runner/work/BlogByHexo/BlogByHexo/node_modules/hexo/lib/extend/filter.js:67:52
    at tryCatcher (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/home/runner/work/BlogByHexo/BlogByHexo/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)
[Aurora Code Filtering Error] Code language: [c++] is not supported.
[Aurora Code Filtering Error] Code language: [c++] is not supported.
[Aurora Code Filtering Error] Code language: [c++] is not supported.
```
所有的文章中，用到了json,python,C,C++,bash以及空白类型的代码，检查日志只发现C和C++代码不能被支持；
在主题配置文件中的配置如下：
```yml
shiki:
  enable: true
  theme: dracula
  externalTheme:
  backgroundColor: '#1a1a1a'
```
全局配置中的高亮已经关闭

**Comment by bennyxguo** [comment]
C 是支持的，C++ 就算不支持也不会生成不成功的。这里有所有支持的语言列表 https://github.com/shikijs/shiki/blob/main/docs/languages.md

C 的话，你改成小写 c 就可以了。你报错的原因是这个 mathjax 导致的：https://github.com/next-theme/hexo-filter-mathjax/issues/26

**Comment by Tim-Saijun** [comment]
感谢，问题解决步骤如下:
## 问题一：[Aurora Code Filtering Error] Code language: [c++] is not supported.
将c++,C++,C等不在列表支持的语言换成cpp和c
## 问题二：Error: Can't find handler for document  at HandlerList.handlesDocument
是mathjax与文章里的一些html代码冲突，关闭全局渲染，只对有数学公式需要的文章渲染即可
