### ISSUE TITLE
版本升级后出现marked.js问题(Cannot read properties of undefined (reading 'length'))

### ISSUE THREAD

**Issue by XinLin-Flow** [auroral-ui/hexo-theme-aurora#374]
输入 hexo g 后：

INFO  Validating config
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read properties of undefined (reading 'length')
Please report this to https://github.com/markedjs/marked.
    at l (/home/blogs/node_modules/fenceparser/dist/index.cjs:1:384)
    at w (/home/blogs/node_modules/fenceparser/dist/index.cjs:1:850)
    at lex (/home/blogs/node_modules/fenceparser/dist/index.cjs:1:1076)
    at parseFence (/home/blogs/node_modules/hexo-plugin-aurora/lib/highlighter/index.js:64:18)
    at Renderer.renderer.code (/home/blogs/node_modules/hexo-plugin-aurora/lib/highlighter/index.js:119:19)
    at Parser.parse (/home/blogs/node_modules/marked/lib/marked.cjs:2158:34)
    at parse (/home/blogs/node_modules/marked/lib/marked.cjs:2088:19)
    at /home/blogs/node_modules/marked/lib/marked.cjs:2509:18
    at marked (/home/blogs/node_modules/marked/lib/marked.cjs:2524:48)
    at Hexo.module.exports (/home/blogs/node_modules/hexo-renderer-marked/lib/renderer.js:247:20)
    at Hexo.tryCatcher (/home/blogs/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/blogs/node_modules/bluebird/js/release/method.js:15:34)
    at /home/blogs/node_modules/hexo/lib/hexo/render.js:81:22
    at tryCatcher (/home/blogs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/blogs/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/blogs/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/home/blogs/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/home/blogs/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/home/blogs/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/blogs/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/blogs/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
INFO  Thanks for using: hexo-plugin-aurora v1.8.2 & hexo-theme-aurora v2.5.0
INFO  Crafted by bennyxguo <三钻>

**Comment by bennyxguo** [comment]
在下一个 hexo-plugin-aurora 版本修复。

**Comment by bennyxguo** [comment]
v1.8.3 hexo-plugin-aurora 修复了这个问题 https://github.com/auroral-ui/hexo-plugin-aurora/releases/tag/v1.8.3
