### ISSUE TITLE
启动hexo时，报错需要堆栈

### ISSUE THREAD

**Issue by LeiYihan01** [auroral-ui/hexo-theme-aurora#399]
我使用hexo s时（用cmd），报错ERROR Plugin load failed: hexo-plugin-aurora，然后说
Error: Cannot find module 'shiki'
Require stack:
- D:\hexo\blog\node_modules\.store\hexo-plugin-aurora@1.8.3\node_modules\hexo-plugin-aurora\lib\highlighter\index.js
- D:\hexo\blog\node_modules\.store\hexo-plugin-aurora@1.8.3\node_modules\hexo-plugin-aurora\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (D:\hexo\blog\node_modules\.store\hexo-plugin-aurora@1.8.3\node_modules\hexo-plugin-aurora\lib\highlighter\index.js:1:15)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at req (D:\hexo\blog\node_modules\hexo\lib\hexo\index.js:292:23)
    at D:\hexo\blog\node_modules\.store\hexo-plugin-aurora@1.8.3\node_modules\hexo-plugin-aurora\index.js:6:1
    at D:\hexo\blog\node_modules\hexo\lib\hexo\index.js:305:14
    at tryCatcher (D:\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\hexo\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\hexo\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\hexo\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\hexo\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\hexo\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\hexo\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\hexo\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (D:\hexo\blog\node_modules\bluebird\js\release\async.js:15:14)
怎么办？？?

**Comment by LeiYihan01** [comment]
附图
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/140927739/36f27ab9-7450-4948-8e4b-a1112023dc35)

**Comment by bennyxguo** [comment]
重新安装一下主题包试试：

```shell
npm install hexo-plugin-aurora@latest hexo-theme-aurora@latest
```

**Comment by LeiYihan01** [comment]
由于服务器在国内访问较慢，我使用cnpm镜像，按照方法重新安装后，还是报错。
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/140927739/3888a57b-d53e-4b3b-be19-3da36bb88373)
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/140927739/b7ddf29a-cd9d-4133-aad2-ddd775e9e2bf)

**Comment by bennyxguo** [comment]
cnpm 有可能有使用问题哦，推荐用 taobao 镜像。https://juejin.cn/post/6844904105572335630

**Comment by LeiYihan01** [comment]
感谢，成功了！
